### ISSUE TITLE
workaround for pagetopdf.jar exceptions

### ISSUE THREAD

**Issue by bertsky** [JKamlah/ocrd_pagetopdf#18]
Currently, the PageToPdf.jar backend from PRImA does not signal exceptions with a non-zero exit status, cf. https://github.com/PRImA-Research-Lab/prima-page-to-pdf/issues/5.

Could we try to do some workaround this from here for the time being?

Options I can see:
- parse stdout for exceptions
- check the resulting PDF file to be non-zero in size (i.e. `-s "$out_file"` instead of `-f "$out_file"`)

**Comment by kba** [comment]
> Options I can see:
> 
> * parse stdout for exceptions
> * check the resulting PDF file to be non-zero in size (i.e. `-s "$out_file"` instead of `-f "$out_file"`)

I think the second solution is probably the least-hacky :+1:
