### ISSUE TITLE
allow creating multi-page PDFs

### ISSUE THREAD

**Issue by bertsky** [JKamlah/ocrd_pagetopdf#5]
IIUC the package currently aims to create one PDF file per page in the output file group.

It would be a thrill to have an option to concatenate all pages into one multi-page PDF file (with proper PDF meta-data about the physical page numbers).

**Comment by JKamlah** [comment]
Adding the option to generate a multipage pdf shouldn't be this hard. With proper meta-dat, idk.

**Comment by bertsky** [comment]
Note that `prima-page-to-pdf` already has a [multi-page mode](https://github.com/PRImA-Research-Lab/prima-page-to-pdf/blob/f485b4cadf0252ec1df00b03004bc8d1bc12fba0/src/org/primaresearch/pdf/CommandLineTool.java#L146). However, it is somewhat restrictive:

- it assumes the `-xml` argument is a directory name, filtering files in there ending with `.xml`
- it assumes the `-image` argument is a directory name (possibly the same), matching the PAGE-XML filenames to it, with `.xml` replaced by either `.jpg`, `.png` or `.tif`
- when an image file is missing (or has another type or filename), then both arrays will become inconsistent (without proper warning)

This is not good enough for our general OCR-D requirements though. (Files can have arbitrary names, they are merely linked by their METS pageId.)

So we should instead merge the individual PDF files into one, maybe with `pdfunite` from libpoppler?

**Comment by bertsky** [comment]
> So we should instead merge the individual PDF files into one, maybe with `pdfunite` from libpoppler?

Or with `pdfjoin` from [pdfjam](http://go.warwick.ac.uk/pdfjam), which also allows to use the original physical `pageId` strings.

**Comment by bertsky** [comment]
> > So we should instead merge the individual PDF files into one, maybe with `pdfunite` from libpoppler?
> 
> Or with `pdfjoin` from [pdfjam](http://go.warwick.ac.uk/pdfjam), which also allows to use the original physical `pageId` strings.

Or do everything in Python with [PyPDF2](https://github.com/mstamy2/PyPDF2), both joining the PDF pages and adding meta-data from METS. (Cmp. [this SO answer](https://stackoverflow.com/a/49053629))

**Comment by JKamlah** [comment]
I am currently working on a solution just with a little python script and gs (ghostscript), which seems to provide everything we need and the user doesn't need install an extra library. But i can also use PyPDF2 instead.

**Comment by bertsky** [comment]
> I am currently working on a solution just with a little python script and gs (ghostscript), which seems to provide everything we need and the user doesn't need install an extra library.

If gs is already needed by the PRImA lib and also allows setting meta-data, then that would be perfect. Anyway, these were just suggestions...

**Comment by JKamlah** [comment]
So a first version is implemented: 659cd280539ebe20b4a8070aee2bd24b44cac845
I need to know what exactly for information are required to write to the pdf. I could name the page as their "pageid" or maybe as their "physicalPagenumber"? And i added the option to add automatically or manually more metadata e.g.  author, title ..

**Comment by JKamlah** [comment]
I added also a little feature, that if the pdf already exist in the mets file, that it gets removed and created new. idk if there is an offical "ocr-d-way"?

**Comment by bertsky** [comment]
> So a first version is implemented: [659cd28](https://github.com/JKamlah/ocrd_pagetopdf/commit/659cd280539ebe20b4a8070aee2bd24b44cac845)

Nice!

I'll look into it. (Hint: next time if you commit your changes into a feature branch and then open a PR on it, then you can ask others for a review, discussing changes with them and making commit suggestions or even adding commits.)

**Comment by bertsky** [comment]
> I need to know what exactly for information are required to write to the pdf. I could name the page as their "pageid" or maybe as their "physicalPagenumber"?

The `pageId` exposed by `ocrd workspace` should be identical to the physical page ID in the METS structMap. And yes, that would be ideal for the PDF page name (as the document structure meta-data like TOC will later refer to those).

> And i added the option to add automatically or manually more metadata e.g. author, title ..

Great. We can work it from there. There's a whole trove of information in the MODS...

> I added also a little feature, that if the pdf already exist in the mets file, that it gets removed and created new. idk if there is an offical "ocr-d-way"?

I saw it. No, that's not OCR-D conforming. (Everything is supposed to be just additive, except if the user wants to destroy annotations.)

There's a long-standing [issue](https://github.com/OCR-D/core/issues/434) on allowing processors to overwrite their output file group with an additional option.

But for now, the user is expected to `workspace remove` or `workspace remove-group` herself.

**Comment by JKamlah** [comment]
So i did some reworks for the multipage option.
Thanks for the hints in the previews push.
