### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by stweil** [JKamlah/ocrd_pagetopdf#9]
The LICENSE file is currently missing.

The code is based on the PRImA PAGE to PDF Converter ([restrictive license](https://github.com/UB-Mannheim/ocrd_pagetopdf/blob/master/ptp/copyright.txt), [Apache 2.0](https://github.com/PRImA-Research-Lab/prima-page-to-pdf/blob/master/LICENSE.md)) which uses itextpdf ([AGPL](https://github.com/itext/itextpdf/blob/develop/LICENSE.md)) and refers to the [DejaVu fonts license](https://web.archive.org/web/20161003100828/http://dejavu-fonts.org/wiki/License).

**Comment by JKamlah** [comment]
So should we add an Apache 2.0 license also? The other copyright information is still in the code available..

**Comment by stweil** [comment]
Yes, I think adding that license would be good.

**Comment by JKamlah** [comment]
Apache-2.0 License added

**Comment by stweil** [comment]
So it looks like the code is ready for an official first release now.
